'''
    show_points.py

    Program to show points generated by generate_points.
'''
import sys


import graphics
import point_utils
import point


def show_points(in_file, size: int):
    ''' Display points produced by generate_points.py'''
    margin = 10
    window_size = 600
    win = graphics.GraphWin("Points",
            window_size + 2 * margin,
            window_size + 2 * margin)
    win.setCoords(-margin, -margin,
            window_size + margin,
            window_size + margin)
    pts: list[point.Point] = point_utils.read_points(in_file)
    for pt in pts:
        x = (pt.x / size) * window_size
        y = (pt.y / size) * window_size
        graphics.Circle(graphics.Point(x, y), 2).draw(win)
    win.getMouse()
    win.close()


def main(argv):
    ''' main function '''
    if len(argv) < 2:
        print("usage: show_points <pointfile> <size>")
        print("    Display the points in <pointfile> in")
        print("    a 600x600 window, mapped as <size>x<size>.")
        sys.exit()

    in_file = open(argv[1], "r", encoding="utf_8")
    size = int(argv[2])
    show_points(in_file, size)
    in_file.close()


if __name__ == "__main__":
    main(sys.argv)
